name: "CI: redsumer-core"

on:
  workflow_run:
    workflows:
      - "CI: Workspace"
    types:
      - completed
  push:
    branches:
      - main
    paths:
      - "redsumer-core/**"
  pull_request:
    branches:
      - main
    paths:
      - "redsumer-core/**"

env:
  PACKAGE_NAME: redsumer-core
  MIN_LINE_COVERAGE_TARGET: 99

jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - name: "Repository: Fetch"
        uses: actions/checkout@v4

      - name: "Setup: Install Rust"
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy

      - name: "Step: Format"
        run: cargo fmt --package ${{ env.PACKAGE_NAME }} --check

      - name: "Step: Lints"
        run: cargo clippy --package ${{ env.PACKAGE_NAME }} --all-features

      - name: "Step: Build"
        run: cargo build --package ${{ env.PACKAGE_NAME }} --all-features

  Docs:
    runs-on: ubuntu-20.04
    needs: Build
    steps:
      - name: "Repository: Fetch"
        uses: actions/checkout@v4

      - name: "Setup: Install Rust"
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: "Step: Build Doc"
        run: cargo doc --package ${{ env.PACKAGE_NAME }} --all-features --document-private-items --verbose

      - name: "Step: Doc Tests"
        run: cargo test --package ${{ env.PACKAGE_NAME }} --all-features --doc

  Tests:
    runs-on: ubuntu-20.04
    needs: Build
    steps:
      - name: "Repository: Fetch"
        uses: actions/checkout@v4

      - name: "Setup: Install Rust, cargo-llvm-cov and cargo-nextest"
        uses: taiki-e/install-action@v2.33.22
        with:
          tool: cargo-llvm-cov,cargo-nextest

      - name: "Step: Tests"
        run: cargo llvm-cov nextest --package ${{ env.PACKAGE_NAME }} --all-features --show-missing-lines --summary-only --fail-under-lines ${{ env.MIN_LINE_COVERAGE_TARGET }}
