name: "CI: Workspace"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 5 * * 0"

jobs:
  Config:
    runs-on: ubuntu-24.04
    steps:
      - name: "Repository: Fetch"
        uses: actions/checkout@v4

      - name: "Setup: Install Rust"
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: "Setup: Install Go"
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: false

      - name: "Setup: Install Taplo"
        uses: taiki-e/install-action@v2
        with:
          tool: taplo-cli

      - name: "Setup: Install yamlfmt"
        run: go install github.com/google/yamlfmt/cmd/yamlfmt@latest

      - name: "Step: Verify YAML Files Format"
        run: yamlfmt --lint .

      - name: "Step: Verify TOML Files Format"
        run: taplo fmt --check --diff --verbose

      - name: "Step: Verify Crates Manifest"
        run: cargo verify-project --verbose

  Security:
    runs-on: ubuntu-24.04
    needs: Config
    steps:
      - name: "Repository: Fetch"
        uses: actions/checkout@v4

      - name: "Step: Security Analysis For Rust"
        uses: EmbarkStudios/cargo-deny-action@v1
        with:
          command: check
          arguments: --workspace --all-features
